# Generated by Django 5.1.7 on 2025-03-17 12:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2048, null=True, verbose_name='课程概述'),
        ),
    ]
