# Generated by Django 5.1.7 on 2025-03-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_activity_coursediscounttype_coursediscount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('expire_time', models.IntegerField(blank=True, null=True, verbose_name='有效期数值')),
                ('expire_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='有效期提示文本')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='课程价格')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_expire', to='Course.course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程有效期选项',
                'verbose_name_plural': '课程有效期选项',
                'db_table': 'sk_course_expire',
            },
        ),
    ]
